{{- if .Values.controller.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: {{ template "swoll.fullname" . }}-controller
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "swoll.labels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "swoll.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "swoll-controller.serviceAccountName" .}}
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - swoll
        - controller
        - --enable-leader-election
        - --image
        - "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
{{- end -}}
