{{- if .Values.controller.enabled -}}
{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "swoll-controller.serviceAccountName" . }}
{{- end }}
{{- end -}}
