criEndpoint: /run/containerd/containerd.sock
image:
  repository: criticalstack/swoll
  tag: latest
  pullPolicy: Always

server:
  enabled: true 
  service:
    type: NodePort
    port: 9095
    targetPort: 9095
    nodePort: 32095
  enablePrometheus: true
  serviceAccount:
    create: true

controller:
  enabled: true
  serviceAccount:
    create: true
